### PR TITLE
Refactor db migrations

### PR DESCRIPTION
**Pull request by satoryu**
Now `database.yml` is kept being managed under git. This situation might cause leaking some developer's root password of mysql or have messed developers up. Actually, I faced with the following error when executing `rake db:create db:migrate` just after `git clone`d. This morning :sunrise: I had been struggling with fixing this issue to launch this rails app :feelsgood: for an hour.

```
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `avatar_content_type' for #<User:0x007f9c1dbc85e8>/path/to/open-slideshare-v2/db/migrate/20151204125053_add_initial_user_data.rb:4:in `up'
NoMethodError: undefined method `avatar_content_type' for #<User:0x007f9c1dbc85e8>
/path/to/open-slideshare-v2/db/migrate/20151204125053_add_initial_user_data.rb:4:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

This pull request will apply the following solutions: 
* Ignore `database.yml` and put `dabase.yml.sample` in `config` directory. 
* Use `db/seeds.rb` and `rake db:seed` instead of `db:migrations` to generates initial data for testing.

### CODE REVIEW

**Comment by ryuzee** [comment]
@satoryu Thanks for sending a PR.

Ignoring database.yml will affect on the deploy procedure.
I'm now considering to replace these hard-coded variables to environmental variables that start with `OSS_` such as `OSS_DB_USERNAME`, `OSS_DB_PASSWORD`. By doing that, it will be easy to pack this application into Docker Image.

**Comment by satoryu** [comment]
Sounds great! As for database connection, it's better to use `DATABASE_URL`. ActiveRecord refers to its value prior to `config/database.yml` [[here]](https://github.com/rails/rails/blob/v4.2.5/activerecord/lib/active_record/connection_handling.rb#L73-L80) .

**Comment by satoryu** [comment]
As I and @ryuzee discussed on Facebook, I'll send two different PRs as this PR has two topic.

**Comment by ryuzee** [comment]
@satoryu Thanks for taking my comments into consideration!!

**Pull request closed without merging**
